---
__postgresql_version: "96"
__postgresql_data_dir: "/var/lib/pgsql96/data"
__postgresql_bin_path: "/usr/bin"
__postgresql_config_path: "/var/lib/pgsql96/data"
__postgresql_daemon: postgresql96
__postgresql_packages:
  - postgresql
  - postgresql96-server
  - postgresql-contrib
  - postgresql-libs
