---

- hosts: bastion
  gather_facts: False
  tasks:
  - name: Create frontend instance
    include_role:
      name: aws-provision 
      vars_from: frontend.yaml

  - name: Create app1 instance
    include_role:
      name: aws-provision
      vars_from: app1.yaml

  - name: Create app2 instance
    include_role:
      name: aws-provision
      vars_from: app2.yaml


  - name: Create db instance
    include_role:
      name: aws-provision
      vars_from: db.yaml


