---

- name: Create a server instance on AWS
  ec2:
    key_name: id_rsa
    group: "{{ security_name }}"
    instance_type: t2.micro
    image: ami-efaf0181
    wait: yes
    region: "{{ region }}"
    instance_tag:
      name: "{{ instance_name }}"
      group: "{{ instance_group_name }}"
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
        delete_on_termination: true
    vpc_subnet_id: subnet-d383dbbb
    assign_public_ip: yes
    count_tag:
      name: "{{ instance_name }}"
      group: "{{ instance_group_name }}"
    exact_count: 1
  register: ec2
    
- name: Add new instance to host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: "{{ instance_group_name }}"
  with_items: "{{ ec2.instances }}"

- name: Wait for SSH to come up
  wait_for:
    host: "{{ item.public_dns_name }}"
    port: 22
    delay: 60
    tiemout: 320
    state: started
  with_items: "{{ ec2.instances }}"
