---
  - name: Get a Compute Instance
    os_server_facts:
      cloud: ospcloud
    register: result

  - name: Delete Instance
    os_server:
      cloud: ospcloud
      state: absent
      name: "{{ item.name }}"
    with_items:
      - "{{ result.ansible_facts.openstack_servers }}"
