---
  - name: Fetch Instance Info
    os_server_facts:
      cloud: ospcloud
      region_name: RegionOne
    register: result

  - degug:
      var: result
    when: result is succeeded


  - fail:
      msg: "this is failed >> {{ result }}"
    when: result is failed
